library(ggplot2)

source('model.R')

get.overview <- function() {
  # Markdown shown in the Overview tab (see get.overview.markdown() in shiny-cea).
  # The text lives in overview.md and describes what simulate() in model.R and
  # this interface do, so it must be kept in sync with them.
  # This function is called long after this file is sourced, when the working
  # directory is no longer the model directory, so overview.md is resolved
  # against the MODEL_PATH set by the app (falling back to the working directory
  # when the interface is used standalone).
  model.dir <- Sys.getenv('MODEL_PATH', unset='.')
  return(paste(readLines(file.path(model.dir, 'overview.md')), collapse='\n'))
}

get.strategies <- function() {
  return(list(
    list(name='no_screening', display.name='No screening'),
    list(name='fit_biennial', display.name='Biennial FIT, 50-74'),
    list(name='colonoscopy_10y', display.name='Colonoscopy every 10 years, 50-79'),
    list(name='colonoscopy_45', display.name='Colonoscopy every 10 years, 45-79')
  ))
}

get.parameters <- function() {
  # Declared in model.R so that the base case has a single source of truth and
  # the model can be run standalone.
  return(MODEL.PARAMETERS)
}

get.strata <- function() {
  return(MODEL.STRATA)
}

get.model.settings <- function() {
  return(list(
    cost.unit='€',
    effectiveness.unit='QALY'
  ))
}

run.simulation <- function(strategies, pars) {
  # simulate() takes the parameters as the named list the app already builds,
  # and copes with any of them arriving as one value per stratum.
  return(simulate(strategies, pars))
}

# Strata used for calibration: all of them.
#
# The cohort starts at age 20 with no lesions, so the first stratum is burn-in
# and its cancer incidence is essentially zero whatever the parameters. It is
# excluded from the targets, which is the documented way of leaving a stratum
# out of the error, rather than from the scheme's strata: the app builds the
# initial guess from the base values over *every* stratum
# (`unlist(calib.pars[scheme$parameters])` in shiny_calibration.R), so a scheme
# that calibrates a subset of the strata gets a longer vector than it consumes
# and every value ends up on the wrong stratum.
CALIB.STRATA <- MODEL.STRATA

# Targets, in the range the literature reports for a population without
# screening: cancer incidence and the stage distribution at diagnosis are
# registry-like figures, lesion prevalence is what colonoscopy and autopsy
# studies find at the same ages. All three refer to the same cohort, which is
# what ties the two pathways together.
#
# They were generated by running the model on a known parameter set and rounding
# (see tests/reference_solution.R), so the exercise has a global optimum with an
# error of about 1e-5 and an optimizer that stops well above it has genuinely
# been trapped rather than run out of model.
CALIB.TARGET <- list(
  `CRC incidence`=list(
    `30-39`=0.000114,
    `40-49`=0.000365,
    `50-59`=0.000867,
    `60-69`=0.001720,
    `70-79`=0.002820,
    `80-89`=0.003980
  ),
  `Adenoma prevalence`=list(
    `30-39`=0.0742,
    `40-49`=0.1490,
    `50-59`=0.2510,
    `60-69`=0.3560,
    `70-79`=0.4430,
    `80-89`=0.5090
  ),
  `Late-stage share`=list(
    `30-39`=0.649,
    `40-49`=0.629,
    `50-59`=0.593,
    `60-69`=0.567,
    `70-79`=0.555,
    `80-89`=0.549
  )
)

# The calibration vector is laid out parameter by parameter, and within a
# parameter stratum by stratum. That is the order the app builds its initial
# guess in and the order the calibrated values are reported in, so the initial
# guess below and the constraints on the vector follow it too.
initial.guess.for <- function(params) {
  base <- default.parameters()
  unname(unlist(lapply(params, function(param) {
    sapply(CALIB.STRATA, function(stratum) base[[param]][[stratum]])
  })))
}

CALIB.PARAMS.CORE <- c('p.adenoma.onset', 'p.ssl.onset')
CALIB.PARAMS.FULL <- c('p.adenoma.onset', 'p.ssl.onset', 'p.aa.progress')

get.calibration.schemes <- function() {
  return(list(
    natural_history=list(
      description=CALIB.DESCRIPTION.FULL,
      parameters=CALIB.PARAMS.FULL,
      target=CALIB.TARGET,
      strata=CALIB.STRATA,
      initial_guess=initial.guess.for(CALIB.PARAMS.FULL),
      error_function=calibration.error,
      latent_space_training_set=generate.training.dataset,
      other.plots=list(plot.pathway.split)
    ),
    pathway_mix=list(
      description=CALIB.DESCRIPTION.CORE,
      parameters=CALIB.PARAMS.CORE,
      target=CALIB.TARGET,
      strata=CALIB.STRATA,
      initial_guess=initial.guess.for(CALIB.PARAMS.CORE),
      error_function=calibration.error,
      latent_space_training_set=generate.training.dataset,
      other.plots=list(plot.pathway.split)
    ),
    constrained=list(
      description=CALIB.DESCRIPTION.CONSTRAINED,
      parameters=CALIB.PARAMS.FULL,
      target=CALIB.TARGET,
      strata=CALIB.STRATA,
      initial_guess=initial.guess.for(CALIB.PARAMS.FULL),
      error_function=calibration.error,
      constraints=calibration.constraints,
      constraints_description=calibration.constraints.llm,
      latent_space_training_set=generate.constrained.training.dataset,
      other.plots=list(plot.pathway.split)
    )
  ))
}

# Turn a calibration vector into the full parameter list the model runs on. The
# app does this itself before it calls the error function; this copy is what
# tests/calibration_landscape.R evaluates the error on over its own grid.
calib.vector.to.parameters <- function(x, params) {
  pars <- default.parameters()
  i <- 1
  for (param in params) {
    for (stratum in CALIB.STRATA) {
      pars[[param]][[stratum]] <- x[[i]]
      i <- i + 1
    }
  }
  return(pars)
}

# Constraints for the constrained scheme, in the c(x) <= 0 convention. They are
# evaluated on the raw calibration vector, so they read it in the layout
# described above: one block per parameter in the order of CALIB.PARAMS.FULL,
# each block holding one value per stratum.
# They encode what is known about the natural history independently of the
# targets: lesion onset and malignant progression do not decrease with age, and
# the serrated pathway stays a minority of all lesions. Together they rule out
# the age-jagged and serrated-dominated fits that match the targets equally well
# but are not clinically credible.
calibration.constraints <- function(x) {
  x <- as.numeric(x)
  n.strata <- length(CALIB.STRATA)
  block <- function(param) {
    j <- match(param, CALIB.PARAMS.FULL)
    x[((j - 1) * n.strata + 1):(j * n.strata)]
  }
  monotonic <- function(param) {
    values <- block(param)
    head(values, -1) - tail(values, -1)
  }
  adenoma <- block('p.adenoma.onset')
  ssl <- block('p.ssl.onset')
  c(
    monotonic('p.adenoma.onset'),
    monotonic('p.ssl.onset'),
    monotonic('p.aa.progress'),
    sum(ssl) - 0.35 * sum(adenoma)
  )
}

# The same constraints in words: the app's agentic_constrained wrapper calls
# this with no arguments and appends the string to the agent's system prompt.
calibration.constraints.llm <- function() {
  n <- length(CALIB.STRATA)
  paste0(
    'The vector holds ', paste(CALIB.PARAMS.FULL, collapse=', '), ', in that ',
    'order, each as a block of ', n, ' values running over the age groups ',
    paste(CALIB.STRATA, collapse=', '), '.\n',
    'Every block is non-decreasing: no value is smaller than the one before it.\n',
    'Total p.ssl.onset is at most 35% of total p.adenoma.onset.'
  )
}

# Relative squared error, averaged within each target series and summed over
# series. Series are on very different scales (incidence is per mil, the stage
# distribution is a proportion), so the error has to be scale free for all three
# to matter.
calibration.error <- function(pars, target) {
  calibration.strategy <- 'no_screening'
  result <- tryCatch({
    results <- run.simulation(calibration.strategy, pars)
    simulated <- results$outputs[[calibration.strategy]]

    error <- 0
    output <- list()
    for (series in names(target)) {
      target.values <- unlist(target[[series]])
      simulated.values <- simulated[[series]][names(target.values)]
      error <- error + mean(((simulated.values - target.values) / target.values)^2)
      output[[series]] <- simulated.values
    }
    list(error=error, output=output)
  }, error=function(e) {
    output <- lapply(target, function(series) {
      values <- rep(NA_real_, length(series))
      names(values) <- names(series)
      values
    })
    list(error=Inf, output=output)
  })
  return(result)
}

# Training set for the latent space methods: the initial guess scaled by a
# uniform random factor per parameter, kept inside [0, 1] as every calibrated
# parameter is an annual probability.
generate.training.dataset <- function(initial_guess, n, ...) {
  f.pars <- list(...)
  variation <- f.pars$variation
  if (is.null(variation)) variation <- 1

  n_params <- length(initial_guess)
  dataset <- matrix(NA_real_, nrow=n, ncol=n_params)
  for (i in 1:n) {
    factors <- runif(n_params, min=max(0, 1-variation), max=1+variation)
    dataset[i,] <- pmin(1, pmax(0, initial_guess * factors))
  }
  dataset <- dataset[sample(nrow(dataset)),]
  return(dataset)
}

# Same, but only feasible points: the constraints are what the embedding is
# meant to learn, so every row is made monotonic in age and is rejected unless
# the serrated pathway stays a minority.
generate.constrained.training.dataset <- function(initial_guess, n, ...) {
  f.pars <- list(...)
  variation <- f.pars$variation
  if (is.null(variation)) variation <- 1

  n_params <- length(CALIB.PARAMS.FULL)
  n_strata <- length(CALIB.STRATA)
  dataset <- matrix(NA_real_, nrow=n, ncol=n_params*n_strata)

  block <- function(j) ((j-1)*n_strata + 1):(j*n_strata)

  i <- 1
  attempts <- 0
  while (i <= n && attempts < 100*n) {
    attempts <- attempts + 1
    factors <- runif(n_params*n_strata, min=max(0, 1-variation), max=1+variation)
    candidate <- pmin(1, pmax(0, initial_guess * factors))
    # Sorting each parameter over the strata makes the row monotonic in age
    # without discarding it.
    for (j in seq_len(n_params)) candidate[block(j)] <- sort(candidate[block(j)])
    adenoma <- candidate[block(1)]
    ssl <- candidate[block(2)]
    if (sum(ssl) > 0.35 * sum(adenoma)) next
    dataset[i,] <- candidate
    i <- i + 1
  }
  if (i <= n) dataset <- dataset[seq_len(i-1),, drop=FALSE]

  dataset <- dataset[sample(nrow(dataset)),, drop=FALSE]
  return(dataset)
}

# Extra calibration plot: the two lesion onset curves the calibration is
# choosing between, which is where the ambiguity of this model lives.
plot.pathway.split <- function(data) {
  series <- function(param) {
    values <- data[startsWith(names(data), paste0(param, '.'))]
    if (length(values) == 0) return(NULL)
    data.frame(stratum=sub(paste0(param, '.'), '', names(values), fixed=TRUE),
               value=as.numeric(values),
               parameter=param)
  }
  plt.df <- do.call(rbind, Filter(Negate(is.null),
                                  list(series('p.adenoma.onset'), series('p.ssl.onset'))))
  if (is.null(plt.df)) return(NULL)

  plt <- ggplot(plt.df, aes(x=stratum, y=value, group=parameter, colour=parameter)) +
    geom_point() +
    geom_line() +
    labs(x='Age group', y='Annual probability of lesion onset', colour='') +
    theme_minimal() +
    theme(legend.position='bottom')
  return(plt)
}

# Scheme descriptions. The app shows these as the label of the scheme, so they
# are short titles; the modelling detail behind each one is in the comments.

# Onset of the two lesion types that drive colorectal cancer here, one value per
# ten-year age group. Both count towards lesion prevalence and both end up as
# cancer, but a serrated lesion gets there several times faster, so incidence
# constrains a weighted sum of the onsets and prevalence their unweighted sum:
# the targets leave a family of pathway mixes that fit almost equally well, and
# only the advanced-stage share tells them apart, weakly.
CALIB.DESCRIPTION.CORE <- 'Two-pathway lesion onset'

# Adds the annual probability that an advanced adenoma becomes cancer. Onset and
# progression compensate each other along a ridge in incidence while prevalence
# depends mostly on onset, and faster progression brings diagnoses forward, so
# raising it can improve one age group and worsen the next.
CALIB.DESCRIPTION.FULL <- 'Lesion onset and progression'

# Same parameters as the full scheme, restricted to fits that are non-decreasing
# in age and keep serrated onset a minority (at most 35% of adenoma onset),
# which excludes the age-jagged and serrated-dominated fits.
CALIB.DESCRIPTION.CONSTRAINED <- 'Constrained onset and progression'

# ### TEST
#
# strategies <- sapply(get.strategies(), function(s) s$name)
# pars <- default.parameters()
# results <- run.simulation(strategies, pars)
# print(results$summary)
# print(calibration.error(pars, CALIB.TARGET)$error)
