# Reference solution of the calibration exercise.
#
# The calibration targets shipped in shiny_interface.R were generated by running
# the model on the parameter set below and rounding the outputs to three
# significant digits, so the calibration has a known global optimum with an
# error of about 1e-5 rather than an unknown floor. That makes it possible to
# tell a genuine failure of an optimizer from a limitation of the model.
#
# This file lives under tests/ on purpose: the agentic calibrator reads the
# model source to build its prompt and skips that directory, so the answer is
# not handed to it.
#
# Run it to regenerate the targets after changing the model:
#   Rscript tests/reference_solution.R

# Run from the repository root.
source('model.R')

# The three calibrated curves at the reference solution. The burn-in stratum
# (20-29) contributes nothing the targets can see, so it is kept at its base
# value: the right answer there is to leave it alone.
TRUE.ADENOMA.ONSET <- c(0.0050, 0.0070, 0.0130, 0.0190, 0.0230, 0.0245, 0.0265)
TRUE.SSL.ONSET <- c(0.00018, 0.00050, 0.00080, 0.00110, 0.00125, 0.00135, 0.00145)
TRUE.AA.PROGRESS <- c(0.0053, 0.0085, 0.0125, 0.0185, 0.0250, 0.0300, 0.0335)

reference.parameters <- function() {
  pars <- default.parameters()
  for (i in seq_along(MODEL.STRATA)) {
    stratum <- MODEL.STRATA[i]
    pars$p.adenoma.onset[[stratum]] <- TRUE.ADENOMA.ONSET[i]
    pars$p.ssl.onset[[stratum]] <- TRUE.SSL.ONSET[i]
    pars$p.aa.progress[[stratum]] <- TRUE.AA.PROGRESS[i]
  }
  return(pars)
}

# The reference solution as the calibration vector the app optimizes over:
# stratum by stratum, and within a stratum in the order the scheme lists its
# parameters.
reference.vector <- function(params=c('p.adenoma.onset', 'p.ssl.onset', 'p.aa.progress')) {
  pars <- reference.parameters()
  unlist(lapply(params, function(param) {
    sapply(MODEL.STRATA, function(stratum) pars[[param]][[stratum]])
  }))
}

# Only when this file is the script being run, not when another one sources it.
run.as.script <- function() {
  file.arg <- grep('^--file=', commandArgs(FALSE), value=TRUE)
  length(file.arg) > 0 && basename(sub('^--file=', '', file.arg[1])) == 'reference_solution.R'
}

if (run.as.script()) {
  results <- simulate('no_screening', reference.parameters())
  outputs <- results$outputs$no_screening
  strata <- MODEL.STRATA[-1]

  cat('# Targets generated from the reference solution\n\n')
  for (series in names(outputs)) {
    values <- signif(outputs[[series]][strata], 3)
    cat(sprintf('  `%s`=list(\n', series))
    cat(paste(sprintf('    `%s`=%s', strata, format(values, scientific=FALSE, trim=TRUE)),
              collapse=',\n'), '\n  ),\n', sep='')
  }
}
